"""add additional fields for user

Revision ID: d80a3c1c045e
Revises: c32dce588c6a
Create Date: 2016-05-26 11:56:02.402599

"""

# revision identifiers, used by Alembic.
revision = 'd80a3c1c045e'
down_revision = 'c32dce588c6a'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('admin', sa.BOOLEAN(), nullable=True))
    op.add_column('users', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('last_login', sa.DateTime(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'last_login')
    op.drop_column('users', 'created_at')
    op.drop_column('users', 'admin')
    ### end Alembic commands ###
